### PR TITLE
update requirements.txt and directory tree

### PR DESCRIPTION
**Pull request by panda1100**
Fixed: Missing packages "lasso-python" and "tqdm"
Fixed: setup.py, after installed, missing vortex_radioss module

With this change, users can install vortex_radioss by the following procedure:
 
git clone https://github.com/Vortex-CAE/Vortex-Radioss.git
pip install ./Vortex-Radioss

Tested on Rocky Linux 9 (EL9)

### CODE REVIEW

**Comment by panda1100** [comment]
Hi @Vortex-CAE, @sebastienVilleneuve and @PaulAltair,
Could you please review this PR?
I'm preparing for OpenRadiossDay 2024 in September.

**Comment by panda1100** [comment]
This is Apptainer definition file `vortex-radioss.def` I used for testing.

```
Bootstrap: docker
From: rockylinux/rockylinux:9

%post
dnf install -y git python3-pip
pip install wheel
cd /opt
git clone https://github.com/panda1100/Vortex-Radioss.git
pip install ./Vortex-Radioss

%runscript
python3 "$@"
```

```
apptainer build vortex-radioss.sif vortex-radioss.def
```

**Comment by Vortex-CAE** [comment]
Thank-you @panda1100! This was something we were meaning to do so this is great! I'll take a look & verify that this installs correctly,

Kind regards,
David

**Comment by Vortex-CAE** [comment]
Thanks @panda1100!

**Pull request merged**
